publish:
  docker:
    registry: 10.20.0.126:5000
    repo: plataforma/base-os
    tag:
      - latest
      - $$BRANCH
      - $$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER
    file: Dockerfile
    insecure: true

cache:
  mount:
    - /drone/docker
